<?php

$data = (
	[ "palavra " => "than" , "traducao" => "do que (comparações)" ],
[ "palavra " => "tell" ,	"traducao" => "dizer" ],
[ "palavra " => "themselves" ,	"traducao" => "eles mesmos" ],
[ "palavra " => "things" ,	"traducao" => "coisas" ],
[ "palavra " => "think" ,	"traducao" => "pensa" ],
[ "palavra " => "though" ,	"traducao" => "embora" ],
[ "palavra " => "thought" ,	"traducao" => "pensamento" ],
[ "palavra " => "through" ,	"traducao" => "através" ],
[ "palavra " => "thus" ,	"traducao" => "assim" ],
[ "palavra " => "took" ,	"traducao" => "fez exame" ],
[ "palavra " => "war" ,	"traducao" => "guerra" ],
[ "palavra " => "way" ,	"traducao" => "percurso, sentido, maneira, modo" ],
[ "palavra " => "went" ,	"traducao" => "foram" ],
[ "palavra " => "whole" ,	"traducao" => "inteiro" ],
[ "palavra " => "would" ,	"traducao" => "futuro condicional" ],
[ "palavra " => "yet" ,	"traducao" => "ainda" ],
[ "palavra " => "about" ,	"traducao" => "sobre, a ponto de, aproximadamente" ],
[ "palavra " => "after" ,	"traducao" => "depois, em seguida" ],
[ "palavra " => "age" ,	"traducao" => "idade" ],
[ "palavra " => "all" ,	"traducao" => "tudo" ],
[ "palavra " => "also" ,	"traducao" => "também" ],
[ "palavra " => "always" ,	"traducao" => "sempre" ],
[ "palavra " => "am" ,	"traducao" => "am" ],
[ "palavra " => "an" ,	"traducao" => "um, uma" ],
[ "palavra " => "and" ,	"traducao" => "e" ],
[ "palavra " => "another" ,	"traducao" => "outros" ],
[ "palavra " => "any" ,	"traducao" => "algum, alguma" ],
[ "palavra " => "are" ,	"traducao" => "são, estão" ],
[ "palavra " => "as" ,	"traducao" => "como, assim como" ],
[ "palavra " => "back" ,	"traducao" => "voltar" ],
[ "palavra " => "be" ,	"traducao" => "ser, estar" ],
[ "palavra " => "because" ,	"traducao" => "porque, por causa" ],
[ "palavra " => "been" ,	"traducao" => "particípio passado to be" ],
[ "palavra " => "before" ,	"traducao" => "antes" ],
[ "palavra " => "between" ,	"traducao" => "entre" ],
[ "palavra " => "body" ,	"traducao" => "corpo" ],
[ "palavra " => "both" ,	"traducao" => "ambos" ],
[ "palavra " => "by" ,	"traducao" => "próximo a, ao lado, perto de, através, por" ],
[ "palavra " => "called" ,	"traducao" => "chamada" ],
[ "palavra " => "can" ,	"traducao" => "poder, ser capaz de" ],
[ "palavra " => "case" ,	"traducao" => "caso" ],
[ "palavra " => "city" ,	"traducao" => "cidade" ],
[ "palavra " => "country" ,	"traducao" => "pais" ],
[ "palavra " => "day" ,	"traducao" => "dia" ],
[ "palavra " => "days" ,	"traducao" => "dias" ],
[ "palavra " => "emperor" ,	"traducao" => "–" ],
[ "palavra " => "end" ,	"traducao" => "fim, final, extremidade" ],
[ "palavra " => "find" ,	"traducao" => "procurar, achado" ],
[ "palavra " => "first" ,	"traducao" => "primeiro" ],
[ "palavra " => "five" ,	"traducao" => "cinco" ],
[ "palavra " => "found" ,	"traducao" => "encontrado" ],
[ "palavra " => "four" ,	"traducao" => "quatro" ],
[ "palavra " => "from" ,	"traducao" => "de" ],
[ "palavra " => "get" ,	"traducao" => "pegar" ],
[ "palavra " => "go" ,	"traducao" => "ir" ],
[ "palavra " => "god" ,	"traducao" => "deus" ],
[ "palavra " => "going" ,	"traducao" => "indo" ],
[ "palavra " => "good" ,	"traducao" => "bom" ],
[ "palavra " => "have" ,	"traducao" => "ter, possuir" ],
[ "palavra " => "having" ,	"traducao" => "tinha" ],
[ "palavra " => "head" ,	"traducao" => "cabeça" ],
[ "palavra " => "heart" ,	"traducao" => "coração" ],
[ "palavra " => "here" ,	"traducao" => "aqui" ],
[ "palavra " => "house" ,	"traducao" => "casa" ],
[ "palavra " => "how" ,	"traducao" => "como" ],
[ "palavra " => "hundred" ,	"traducao" => "cem" ],
[ "palavra " => "if" ,	"traducao" => "se" ],
[ "palavra " => "in" ,	"traducao" => "em, no, na, nos, nas" ],
[ "palavra " => "is" ,	"traducao" => "é, está" ],
[ "palavra " => "it" ,	"traducao" => "ele, ela (objetos e animais)" ],
[ "palavra " => "its" ,	"traducao" => "seu (p/ animais e objetos)" ],
[ "palavra " => "king" ,	"traducao" => "rei" ],
[ "palavra " => "know" ,	"traducao" => "saber" ],
[ "palavra " => "left" ,	"traducao" => "esquerdo, esquerda" ],
[ "palavra " => "life" ,	"traducao" => "vida" ],
[ "palavra " => "light" ,	"traducao" => "luz" ],
[ "palavra " => "like" ,	"traducao" => "gostar, semelhante, parecido" ],
[ "palavra " => "little" ,	"traducao" => "pouco" ],
[ "palavra " => "long" ,	"traducao" => "longo" ],
[ "palavra " => "look" ,	"traducao" => "olhar" ],
[ "palavra " => "love" ,	"traducao" => "amor" ],
[ "palavra " => "man" ,	"traducao" => "homem" ],
[ "palavra " => "many" ,	"traducao" => "muitos" ],
[ "palavra " => "me" ,	"traducao" => "a mim" ],
[ "palavra " => "men" ,	"traducao" => "homens" ],
[ "palavra " => "mind" ,	"traducao" => "mente" ],
[ "palavra " => "more" ,	"traducao" => "mais" ],
[ "palavra " => "most" ,	"traducao" => "mais (superlativo)" ],
[ "palavra " => "mr" ,	"traducao" => "Sr." ],
[ "palavra " => "much" ,	"traducao" => "muito" ],
[ "palavra " => "my" ,	"traducao" => "meu, minha" ],
[ "palavra " => "name" ,	"traducao" => "nome" ],
[ "palavra " => "nature" ,	"traducao" => "natureza" ],
[ "palavra " => "never" ,	"traducao" => "nunca" ],
[ "palavra " => "new" ,	"traducao" => "novo" ],
[ "palavra " => "night" ,	"traducao" => "noite" ],
[ "palavra " => "no" ,	"traducao" => "não, nenhum, nenhuma" ],
[ "palavra " => "not" ,	"traducao" => "negativa, não" ],
[ "palavra " => "nothing" ,	"traducao" => "nada" ],
[ "palavra " => "now" ,	"traducao" => "agora" ],
[ "palavra " => "of" ,	"traducao" => "o, a, os, as" ],
[ "palavra " => "off" ,	"traducao" => "desligado" ],
[ "palavra " => "old" ,	"traducao" => "velho" ],
[ "palavra " => "one" ,	"traducao" => "um, uma" ],
[ "palavra " => "only" ,	"traducao" => "apenas, único, somente" ],
[ "palavra " => "or" ,	"traducao" => "ou" ],
[ "palavra " => "other" ,	"traducao" => "outro, outra" ],
[ "palavra " => "others" ,	"traducao" => "outros" ],
[ "palavra " => "our" ,	"traducao" => "nosso" ],
[ "palavra " => "out" ,	"traducao" => "fora" ],
[ "palavra " => "part" ,	"traducao" => "parte" ],
[ "palavra " => "people" ,	"traducao" => "povos" ],
[ "palavra " => "place" ,	"traducao" => "lugar" ],
[ "palavra " => "power" ,	"traducao" => "potencia, poder" ],
[ "palavra " => "public" ,	"traducao" => "público" ],
[ "palavra " => "right" ,	"traducao" => "direita, direito" ],
[ "palavra " => "roman" ,	"traducao" => "romano" ],
[ "palavra " => "said" ,	"traducao" => " " ],
[ "palavra " => "say" ,	"traducao" => "palavra" ],
[ "palavra " => "see" ,	"traducao" => "ver" ],
[ "palavra " => "she" ,	"traducao" => "ela" ],
[ "palavra " => "side" ,	"traducao" => "lado" ],
[ "palavra " => "soon" ,	"traducao" => "breve" ],
[ "palavra " => "state" ,	"traducao" => "estado" ],
[ "palavra " => "take" ,	"traducao" => "tomada" ],
[ "palavra " => "the" ,	"traducao" => "o, a, os, as" ],
[ "palavra " => "their" ,	"traducao" => "deles, delas" ],
[ "palavra " => "them" ,	"traducao" => "a eles, a elas" ],
[ "palavra " => "there" ,	"traducao" => "há" ],
[ "palavra " => "these" ,	"traducao" => "estes, estas" ],
[ "palavra " => "they" ,	"traducao" => "eles, elas" ],
[ "palavra " => "this" ,	"traducao" => "este, esta" ],
[ "palavra " => "those" ,	"traducao" => "aqueles" ],
[ "palavra " => "three" ,	"traducao" => "tres" ],
[ "palavra " => "time" ,	"traducao" => "tempo, momento" ],
[ "palavra " => "to" ,	"traducao" => "para" ],
[ "palavra " => "twenty" ,	"traducao" => "vinte" ],
[ "palavra " => "two" ,	"traducao" => "dois, duas" ],
[ "palavra " => "up" ,	"traducao" => "para cima" ],
[ "palavra " => "upon" ,	"traducao" => "sobre" ],
[ "palavra " => "us" ,	"traducao" => "nós" ],
[ "palavra " => "very" ,	"traducao" => "muito" ],
[ "palavra " => "water" ,	"traducao" => "água" ],
[ "palavra " => "we" ,	"traducao" => "nós" ],
[ "palavra " => "well" ,	"traducao" => "bem" ],
[ "palavra " => "what" ,	"traducao" => "o que, quais" ],
[ "palavra " => "when" ,	"traducao" => "quando" ],
[ "palavra " => "where" ,	"traducao" => "onde" ],
[ "palavra " => "which" ,	"traducao" => "qual, de qual" ],
[ "palavra " => "while" ,	"traducao" => "quando" ],
[ "palavra " => "who" ,	"traducao" => "quem" ],
[ "palavra " => "whom" ,	"traducao" => "quem" ],
[ "palavra " => "whose" ,	"traducao" => "de quem" ],
[ "palavra " => "will" ,	"traducao" => "futuro" ],
[ "palavra " => "with" ,	"traducao" => "com" ],
[ "palavra " => "without" ,	"traducao" => "sem" ],
[ "palavra " => "woman" ,	"traducao" => "mulher" ],
[ "palavra " => "words" ,	"traducao" => "palavras" ],
[ "palavra " => "work" ,	"traducao" => "trabalho" ],
[ "palavra " => "world" ,	"traducao" => "mundo" ],
[ "palavra " => "years" ,	"traducao" => "anos" ],
[ "palavra " => "you" ,	"traducao" => "você" ],
[ "palavra " => "young" ,	"traducao" => "jovens" ],
[ "palavra " => "your" ,	"traducao" => "seu, seus" ],
[ "palavra " => "almost" ,	"traducao" => "quase" ],
[ "palavra " => "arms" ,	"traducao" => "braços" ],
[ "palavra " => "asked" ,	"traducao" => "pedida" ],
[ "palavra " => "at" ,	"traducao" => "no, na, em, ás" ],
[ "palavra " => "but" ,	"traducao" => "mas, porém, exceto" ],
[ "palavra " => "death" ,	"traducao" => "morte" ],
[ "palavra " => "did" ,	"traducao" => "fazer" ],
[ "palavra " => "do" ,	"traducao" => "fazer, verbo auxiliar" ],
[ "palavra " => "down" ,	"traducao" => "para baixo" ],
[ "palavra " => "each" ,	"traducao" => "cada um" ],
[ "palavra " => "every" ,	"traducao" => "cada" ],
[ "palavra " => "father" ,	"traducao" => "pai" ],
[ "palavra " => "footnote" ,	"traducao" => "notas de rodapé" ],
[ "palavra " => "for" ,	"traducao" => "para, por" ],
[ "palavra " => "general" ,	"traducao" => "geral" ],
[ "palavra " => "great" ,	"traducao" => "grande, maravilhoso" ],
[ "palavra " => "has" ,	"traducao" => "tem" ],
[ "palavra " => "he" ,	"traducao" => "ele" ],
[ "palavra " => "her" ,	"traducao" => "dela" ],
[ "palavra " => "into" ,	"traducao" => "em direção de" ],
[ "palavra " => "last" ,	"traducao" => "último" ],
[ "palavra " => "looked" ,	"traducao" => "olhada" ],
[ "palavra " => "non" ,	"traducao" => "não" ],
[ "palavra " => "nor" ,	"traducao" => "nem" ],
[ "palavra " => "on" ,	"traducao" => "sobre, em cima, em direção a" ],
[ "palavra " => "over" ,	"traducao" => "acima, encerrado" ],
[ "palavra " => "put" ,	"traducao" => "posto" ],
[ "palavra " => "seen" ,	"traducao" => "visto" ],
[ "palavra " => "should" ,	"traducao" => "dever, verbo auxiliar" ],
[ "palavra " => "thousand" ,	"traducao" => "mil" ],
[ "palavra " => "too" ,	"traducao" => "demasiado" ],
[ "palavra " => "under" ,	"traducao" => "sob" ],
[ "palavra " => "until" ,	"traducao" => "até" ],
[ "palavra " => "why" ,	"traducao" => "porque" ]
	);

foreach ($data as $da){
	echo($da['palavra']);
}